/**
 * A list of all event.code values. The function and print screen keys do not
 * trigger the key event. Macro keys probably don't either. Also keys pressed
 * with the function keys down tend to either not trigger at all or else
 * trigger a different key than the hardware key present in that location.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code
 *
 * @type {object}
 */
chroma.key_codes = {
  'Escape': 'escape',
  'F1': 'f1',
  'F2': 'f2',
  'F3': 'f3',
  'F4': 'f4',
  'F5': 'f5',
  'F6': 'f6',
  'F7': 'f7',
  'F8': 'f8',
  'F9': 'f9',
  'F10': 'f10',
  'F11': 'f11',
  'F12': 'f12',
  'ScrollLock': 'scroll_lock',
  'Pause': 'pause',

  'Backquote': 'backquote',
  'Digit1': '1',
  'Digit2': '2',
  'Digit3': '3',
  'Digit4': '4',
  'Digit5': '5',
  'Digit6': '6',
  'Digit7': '7',
  'Digit8': '8',
  'Digit9': '9',
  'Digit0': '0',
  'Minus': 'minus',
  'Equal': 'equal',
  'Backspace': 'backspace',
  'Insert': 'insert',
  'Home': 'home',
  'PageUp': 'page_up',
  'NumLock': 'numpad_num_lock',
  'NumpadDivide': 'numpad_divide',
  'NumpadMultiply': 'numpad_multiply',
  'NumpadSubtract': 'numpad_subtract',

  'Tab': 'tab',
  'KeyQ': 'q',
  'KeyW': 'w',
  'KeyE': 'e',
  'KeyR': 'r',
  'KeyT': 't',
  'KeyY': 'y',
  'KeyU': 'u',
  'KeyI': 'i',
  'KeyO': 'o',
  'KeyP': 'p',
  'BracketLeft': 'bracket_left',
  'BracketRight': 'bracket_right',
  'Backslash': 'backslash',
  'Delete': 'delete',
  'End': 'end',
  'PageDown': 'page_down',
  'Numpad7': 'numpad_7',
  'Numpad8': 'numpad_8',
  'Numpad9': 'numpad_9',
  'NumpadAdd': 'numpad_add',

  'CapsLock': 'caps_lock',
  'KeyA': 'a',
  'KeyS': 's',
  'KeyD': 'd',
  'KeyF': 'f',
  'KeyG': 'g',
  'KeyH': 'h',
  'KeyJ': 'j',
  'KeyK': 'k',
  'KeyL': 'l',
  'Semicolon': 'semicolon',
  'Quote': 'quote',
  'Enter': 'enter',
  'Numpad4': 'numpad_4',
  'Numpad5': 'numpad_5',
  'Numpad6': 'numpad_6',

  'ShiftLeft': 'shift_left',
  'KeyZ': 'z',
  'KeyX': 'x',
  'KeyC': 'c',
  'KeyV': 'v',
  'KeyB': 'b',
  'KeyN': 'n',
  'KeyM': 'm',
  'Comma': 'comma',
  'Period': 'period',
  'Slash': 'slash',
  'ShiftRight': 'shift_right',
  'ArrowUp': 'up',
  'Numpad1': 'numpad_1',
  'Numpad2': 'numpad_2',
  'Numpad3': 'numpad_3',
  'NumpadEnter': 'numpad_enter',

  'ControlLeft': 'control_left',
  'MetaLeft': 'meta',
  'AltLeft': 'alt_left',
  'Space': 'space',
  'AltRight': 'alt_right',
  'ContextMenu': 'context_menu',
  'ControlRight': 'control_right',
  'ArrowLeft': 'left',
  'ArrowDown': 'down',
  'ArrowRight': 'right',
  'Numpad0': 'numpad_0',
  'NumpadDecimal': 'numpad_decimal'
};
